{{- if and (not .Values.config.existingSecret) (or .Values.config.clientSecret .Values.config.adminToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talosctl-oidc.fullname" . }}-config
  labels:
    {{- include "talosctl-oidc.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.clientSecret }}
  client-secret: {{ .Values.config.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.adminToken }}
  admin-token: {{ .Values.config.adminToken | b64enc | quote }}
  {{- end }}
{{- end }}
