{{- if and (not .Values.config.existingSecret) (or .Values.config.clientSecret .Values.config.adminToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talosctl-oidc.fullname" . }}-config
  labels:
    {{- include "talosctl-oidc.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.clientSecret }}
  client-secret: {{ .Values.config.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.adminToken }}
  admin-token: {{ .Values.config.adminToken | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and (not .Values.talos.apiAccess.enabled) (not .Values.talos.caSecretName) .Values.talos.caCert .Values.talos.caKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talosctl-oidc.fullname" . }}-ca
  labels:
    {{- include "talosctl-oidc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.talos.caSecretKeys.cert }}: {{ .Values.talos.caCert | b64enc | quote }}
  {{ .Values.talos.caSecretKeys.key }}: {{ .Values.talos.caKey | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.talos.apiAccess.enabled) (not .Values.talos.caSecretName) .Values.talos.caCertData .Values.talos.caKeyData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talosctl-oidc.fullname" . }}-ca-data
  labels:
    {{- include "talosctl-oidc.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: {{ .Values.talos.caCertData | quote }}
  ca.key: {{ .Values.talos.caKeyData | quote }}
{{- end }}
